# Generated by Django 3.2.8 on 2021-11-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('come_up_biz', '0002_auto_20211106_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='likes_count',
        ),
    ]
